local kind = {
  Namespace = "󰌗",
  Text = "󰉿",
  Method = "󰆧",
  Function = "󰆧",
  Constructor = "",
  Field = "󰜢",
  Variable = "󰀫",
  Class = "󰠱",
  Interface = "",
  Module = "",
  Property = "󰜢",
  Unit = "󰑭",
  Value = "󰎠",
  Enum = "",
  Keyword = "󰌋",
  Snippet = "",
  Color = "󰏘",
  File = "󰈚",
  Reference = "󰈇",
  Folder = "󰉋",
  EnumMember = "",
  Constant = "󰏿",
  Struct = "󰙅",
  Event = "",
  Operator = "󰆕",
  TypeParameter = "󰊄",
  Table = "",
  Object = "󰅩",
  Tag = "",
  Array = "[]",
  Boolean = "",
  Number = "",
  Null = "󰟢",
  String = "󰉿",
  Calendar = "",
  Watch = "󰥔",
  Package = "",
  Copilot = "",
  Codeium = "",
  TabNine = "",
}

nvoid.builtin.cmp.cmdline.enable = true
nvoid.builtin.cmp.formatting.kind_icons = kind
nvoid.builtin.cmp.window.completion.border = { "", "", "", "", "", "", "", "" }
nvoid.builtin.cmp.window.completion.winhighlight = "Normal:Pmenu,CursorLine:PmenuSel,FloatBorder:FloatBorder,Search:None"
nvoid.builtin.cmp.window.completion.side_padding = 0
nvoid.builtin.cmp.window.documentation.border = { "", "", "", "", "", "", "", "" }
nvoid.builtin.cmp.window.documentation.winhighlight =
"Normal:Pmenu,CursorLine:PmenuSel,FloatBorder:FloatBorder,Search:None"
nvoid.builtin.cmp.window.documentation.side_padding = 0
