local nt = nvoid.builtin.nvimtree.setup
nt.view.side = "left"
nt.view.centralize_selection = true
nt.diagnostics.show_on_dirs = true
nt.renderer.indent_markers.enable = true
nt.renderer.icons.glyphs.folder.arrow_open = ""
nt.renderer.icons.glyphs.folder.arrow_closed = ""
nt.sync_root_with_cwd = true
nt.respect_buf_cwd = true
nt.update_focused_file.enable = true
nt.update_focused_file.update_root = true
nt.hijack_netrw = true
