return {
  CmpItemKindConstant = { bg = "orange", fg = "black" },
  CmpItemKindFunction = { bg = "blue", fg = "black" },
  CmpItemKindIdentifier = { bg = "vibrant_green", fg = "black" },
  CmpItemKindField = { bg = "vibrant_green", fg = "black" },
  CmpItemKindVariable = { bg = "purple", fg = "black" },
  CmpItemKindSnippet = { bg = "red", fg = "black" },
  CmpItemKindText = { bg = "green", fg = "black" },
  CmpItemKindStructure = { bg = "purple", fg = "black" },
  CmpItemKindType = { bg = "teal", fg = "black" },
  CmpItemKindKeyword = { bg = "white", fg = "black" },
  CmpItemKindMethod = { bg = "blue", fg = "black" },
  CmpItemKindConstructor = { bg = "blue", fg = "black" },
  CmpItemKindFolder = { bg = "white", fg = "black" },
  CmpItemKindModule = { bg = "teal", fg = "black" },
  CmpItemKindProperty = { bg = "vibrant_green", fg = "black" },
  CmpItemKindUnit = { bg = "purple", fg = "black" },
  CmpItemKindFile = { bg = "white", fg = "black" },
  CmpItemKindColor = { bg = "white", fg = "black" },
  CmpItemKindReference = { bg = "light_grey", fg = "black" },
  CmpItemKindStruct = { bg = "purple", fg = "black" },
  CmpItemKindOperator = { bg = "light_grey", fg = "black" },
  CmpItemKindTypeParameter = { bg = "vibrant_green", fg = "black" },
}
