nvoid.leader = "space"
nvoid.keys.normal_mode["<C-a>"] = "gg<S-v>G"
nvoid.keys.normal_mode["<C-b>"] = ":JABSOpen<CR>"
nvoid.keys.normal_mode["<S-x>"] = ":BufferKill<CR>"
nvoid.keys.normal_mode["<TAB>"] = ":BufferNext<CR>"
nvoid.keys.normal_mode["<S-TAB>"] = ":BufferPrev<CR>"
